// prettier-ignore
module.exports = {
    purge: {
        enabled: false,
        content: [
            './src/**/*.js',
            './src/**/*.jsx',
            './src/**/*.ts',
            './src/**/*.tsx',
            './public/**/*.html',
        ],
    },
    theme: {
        extend: {
            spacing: {
                '10vh': '10vh',
                '20vh': '20vh',
                '30vh': '30vh',
                '40vh': '40vh',
                '50vh': '50vh',
                '60vh': '60vh',
                '70vh': '70vh',
                '80vh': '80vh',
                '90vh': '90vh',
                '100vh': '100vh',
                '10vw': '10vw',
                '15vw': '15vw',
                '20vw': '20vw',
                '30vw': '30vw',
                '40vw': '40vw',
                '50vw': '50vw',
                '60vw': '60vw',
                '70vw': '70vw',
                '80vw': '80vw',
                '90vw': '90vw',
                '100vw': '100vw',

                '56': '14rem',
                '58': '14.5rem',
                '60': '15rem',
                '62': '15.5rem',
                '64': '16rem',
                '66': '16.5rem',
                '68': '17rem',
                '70': '17.5rem',
                '72': '18rem',
            },
        },
    },
};
